# Generated by Django 5.2.7 on 2025-10-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text="Description du pari ou de l'événement sur lequel on vote.")),
                ('nb_oui', models.PositiveIntegerField(default=0, verbose_name='Nombre de votes OUI')),
                ('nb_non', models.PositiveIntegerField(default=0, verbose_name='Nombre de votes NON')),
                ('evenement_arrive', models.BooleanField(default=False, verbose_name="L'événement est-il arrivé ?")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pari',
                'verbose_name_plural': 'Paris',
                'ordering': ['-created_at'],
            },
        ),
    ]
