# Generated by Django 5.2.7 on 2025-10-23 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pari'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
