# Generated by Django 5.2.7 on 2025-10-23 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pari',
            name='description',
            field=models.TextField(help_text='Description du pari.'),
        ),
        migrations.AlterField(
            model_name='pari',
            name='evenement_arrive',
            field=models.BooleanField(default=False, verbose_name='Événement arrivé ?'),
        ),
        migrations.AlterField(
            model_name='pari',
            name='nb_non',
            field=models.PositiveIntegerField(default=0, verbose_name='Votes NON'),
        ),
        migrations.AlterField(
            model_name='pari',
            name='nb_oui',
            field=models.PositiveIntegerField(default=0, verbose_name='Votes OUI'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.pari')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['pari', 'user'], name='core_vote_pari_id_ccce26_idx'), models.Index(fields=['pari', 'choice'], name='core_vote_pari_id_54968f_idx')],
                'unique_together': {('user', 'pari')},
            },
        ),
    ]
