# Generated by Django 5.2.7 on 2025-10-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='stake_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
