# Generated by Django 5.2.7 on 2025-10-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_vote_stake_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pari',
            name='evenement_arrive',
        ),
        migrations.AddField(
            model_name='pari',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pari',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pari',
            name='result',
            field=models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], help_text='Résultat validé (oui/non).', max_length=3, null=True),
        ),
    ]
